# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
	foods = Food.create([{name: 'Bunbo', description: 'This data is almost always never interesting, but completely necessary for the application to work as expected. So when it comes to time send your little baby to production, only to find your users can’t pay because they can’t pick their credit card type, your world comes crashing down.', price: 30000, section_id: 1, image_url: 'http://mongingon.com/wp-content/uploads/2015/03/bi-quyet-nau-bun-bo-hue.jpg'}])
	foods = Food.create([{name: 'Bunca', description: 'This data is almost always never interesting, but completely necessary for the application to work as expected. So when it comes to time send your little baby to production, only to find your users can’t pay because they can’t pick their credit card type, your world comes crashing down.', price: 35000, section_id: 1, image_url: 'http://setupnhahang.bepchien.com/image/data/b%C3%BAn%20c%C3%A1%201.JPG'}])
	foods = Food.create([{name: 'Bunbo', description: 'This data is almost always never interesting, but completely necessary for the application to work as expected. So when it comes to time send your little baby to production, only to find your users can’t pay because they can’t pick their credit card type, your world comes crashing down.', price: 15000, section_id: 1, image_url: 'http://giaoduc.net.vn/Uploaded/haiha/2011_10_11/banh%20mi%201.jpg'}])
	foods = Food.create([{name: 'Banhuot', description: 'This data is almost always never interesting, but completely necessary for the application to work as expected. So when it comes to time send your little baby to production, only to find your users can’t pay because they can’t pick their credit card type, your world comes crashing down.', price: 20000, section_id: 1, image_url: 'https://cdn3.ivivu.com/2014/07/Nhung-quan-banh-uot-va-banh-cuon-tru-danh-cua-Sai-Gon-1-ivivu.jpg'}])
	sections = Section.create([{name: 'Lunch'}])